const players = [
  {
    id: 1,
    name: "Ruturaj Gaikwad",
    team: "Chennai Super Kings",
    role: "Batsman",
    country: "India",
    age: 29,
  },
  {
    id: 2,
    name: "MS Dhoni",
    team: "Chennai Super Kings",
    role: "Wicket Keeper",
    country: "India",
    age: 45,
  },
  {
    id: 3,
    name: "Rohit Sharma",
    team: "Mumbai Indians",
    role: "Batsman",
    country: "India",
    age: 39,
  },
  {
    id: 4,
    name: "Jasprit Bumrah",
    team: "Mumbai Indians",
    role: "Bowler",
    country: "India",
    age: 32,
  },
  {
    id: 5,
    name: "Virat Kohli",
    team: "Royal Challengers Bengaluru",
    role: "Batsman",
    country: "India",
    age: 37,
  },
  {
    id: 6,
    name: "Rajat Patidar",
    team: "Royal Challengers Bengaluru",
    role: "Batsman",
    country: "India",
    age: 33,
  },
  {
    id: 7,
    name: "Sunil Narine",
    team: "Kolkata Knight Riders",
    role: "All Rounder",
    country: "West Indies",
    age: 37,
  },
  {
    id: 8,
    name: "Andre Russell",
    team: "Kolkata Knight Riders",
    role: "All Rounder",
    country: "West Indies",
    age: 38,
  },
  {
    id: 9,
    name: "Sanju Samson",
    team: "Rajasthan Royals",
    role: "Wicket Keeper",
    country: "India",
    age: 31,
  },
  {
    id: 10,
    name: "Pat Cummins",
    team: "Sunrisers Hyderabad",
    role: "Bowler",
    country: "Australia",
    age: 33,
  },
];

export default players;